classes_names = [
    {'id': 'DX6Gr37urTZVQ6fAJesX', 'word': 'acerola'},
    {'id': 'QNyuvW5nA1bDsiugZ4Lp', 'word': 'ackee'},
    {'id': 'wbya8P1qwq09dhUv5Viz', 'word': 'aloe vera'},
    {'id': 'NDzxAH03jFUfiXm9hbt4', 'word': 'ambarella'},
    {'id': 'XhnNCJgMTq4hO467BtA6', 'word': 'apple'},
    {'id': 'NTEOokyJizCbUvFoo8X8', 'word': 'artichokes'},
    {'id': '0LqdBe9Q7OnX4XdJy7Y9', 'word': 'asparagus'},
    {'id': 'IRTZcEhHxOvKn389JqcK', 'word': 'aubergine'},
    {'id': '6OGYpszvuhtIV38ZH0u3', 'word': 'avocado'},
    {'id': 'cThjWwKncS78hP7O0Aij', 'word': 'banana'},
    {'id': 'g6zFhHQL9vmxyMF85Dyr', 'word': 'beetroot'},
    {'id': 'rKvtyaPxFEW5Y1hfDnIb', 'word': 'bell peper'},
    {'id': 'NqJ44Fpwa68fnEBXkqht', 'word': 'betel nut'},
    {'id': '2afw7u0d6GB8tOdJ2u9b', 'word': 'bitter melon'},
    {'id': 'Ceqcf7hwpXSoT7ESDyjT', 'word': 'bread fruit'},
    {'id': 'VQjrt0p6lQdTpZJmmtx7', 'word': 'broccoli'},
    {'id': 'nhQcvyZcsORJXUDPCBlp', 'word': 'brussels sprout'},
    {'id': 'lrBM69ojDy4doMmpdDTp', 'word': "buddha's hand"},
    {'id': 'fbmbMRjPamDZdwuoi6uy', 'word': 'cabbage'},
    {'id': 'FVqylJn1HSzje8tQruxL', 'word': 'cacao'},
    {'id': '7KbzLs3K07vnXzSqLVGi', 'word': 'cantaloupe'},
    {'id': '857ifgvi5HAy1SkHeKom', 'word': 'carrot'},
    {'id': '8lSeJVNYrUltxMWfgKEl', 'word': 'cassava'},
    {'id': 'QqAMiqZGsxZRE1LiTqhw', 'word': 'chayote'},
    {'id': 'iNCOmkHi1DpFzTRlaEI7', 'word': 'cherry'},
    {'id': 'VfH13Tj7roDSUYRwkras', 'word': 'chestnut'},
    {'id': 'B9hT6pa1m83q92Elzufn', 'word': 'chili'},
    {'id': '1Ye9gK9cUewWuhTZG6C3', 'word': 'coconut'},
    {'id': 'DLRypNoQJGnXHsMrPuH6', 'word': 'coffee bean'},
    {'id': 'Pu1igBQFQLWcve1wOcEm', 'word': 'corn'},
    {'id': 'OReHCU0Cke0S4WLhztPf', 'word': 'courgette'},
    {'id': '16BYarBvmMO0WiHdoJzy', 'word': 'cucumber'},
    {'id': 'JY2S7lClk9rXATkpX21P', 'word': 'curly kale'},
    {'id': 'okVO9EcnH7lKndS3uJNN', 'word': 'custard apple'},
    {'id': 'A4KnqZ7syezKyObdEdzq', 'word': 'dragon fruit'},
    {'id': 'NNn4sMMf5uhaaGZo9On6', 'word': 'durian'},
    {'id': 'wDQDNxPCdNaQmZ8TkqLQ', 'word': 'figs'},
    {'id': '3WMQ6n36e5zHYsPAtMpa', 'word': 'gac fruit'},
    {'id': 'Nd75EOsSmTvgWyjOXOX2', 'word': 'garlic'},
    {'id': 'skBB2CLD6DVIcHoTLT6t', 'word': 'ginger'},
    {'id': 'qChvfVkOz49FKU4SabHk', 'word': 'gourd'},
    {'id': 'qx0CqtwFwrRScCwgeZdQ', 'word': 'grape'},
    {'id': 'u9ql2c3bv8Kly2HuGLTX', 'word': 'guava'},
    {'id': 'dubaEdBGe8hd1tZhRMDk', 'word': 'jack fruit'},
    {'id': 'lZOqZPAnUSsvy0UDTPJK', 'word': 'java plum'},
    {'id': 'pGB0xCQh5WimUNWTWyZi', 'word': 'kiwi'},
    {'id': 'KKImRy1pNfQKUFcsIRE2', 'word': 'kohlrabi'},
    {'id': 'hywsCOc88dxwrAkvdFt2', 'word': 'kumquat'},
    {'id': 'VxgEGxnNu7uTd88YSYiE', 'word': 'langsat'},
    {'id': 'Kgt07GnTS1B8n0fxOf5d', 'word': 'lemon'},
    {'id': 'As43oSBdZymlI3v2a4lL', 'word': 'lemon grass'},
    {'id': 'Iqw1gd5QoGfvqSAfk4bJ', 'word': 'longan'},
    {'id': '4ajGt23jxoPmJDq72zz3', 'word': 'loofah'},
    {'id': 'ubfQZPfRwF0fInZGzn9D', 'word': 'loquat'},
    {'id': 'nlnP9GqvuF9B6Df4TLGa', 'word': 'lychee'},
    {'id': 'ORdtNlzzKUKdlYWRwEkl', 'word': 'macadamia'},
    {'id': 'vNXMxDSPrsHICuRYkXSQ', 'word': 'mango'},
    {'id': 'jOjrk4ES0F5xCNU2mftL', 'word': 'mangosteen'},
    {'id': '0EzKd0jpjhkypnYaqUl9', 'word': 'mint'},
    {'id': 'cmzLzz88mIPHemhtyNbD', 'word': 'miracle fruit'},
    {'id': 'kNCawhw14mKM8qehKzZ9', 'word': 'morning glory'},
    {'id': 'Ddl48WRlJ8sf40TgZZ1N', 'word': 'mulberry'},
    {'id': 'i2j03S3kaD135iDY5VWQ', 'word': 'mushroom'},
    {'id': 'n1RWUPa39oUao4iw7SNW', 'word': 'noni fruit'},
    {'id': 'i4T2Ys4lbtxcZt5VrCms', 'word': 'okra'},
    {'id': '1pyi5ZBxPArLgYKnBrQc', 'word': 'onion'},
    {'id': 'FpQ9tcL9jWo8mPWsCR5i', 'word': 'orange'},
    {'id': 'QMYFBJWYxlkpVH4ZWcRz', 'word': 'papaya'},
    {'id': 'iE1tV17qAd8AWUne0yWy', 'word': 'passion fruit'},
    {'id': 'eDXNQtBeE46xbfYdggIl', 'word': 'peaches'},
    {'id': 'St41a0dUn7W61lyzfKcI', 'word': 'peanut'},
    {'id': 'fgZMF6JaDJuct2KsZzv7', 'word': 'pear'},
    {'id': 'rlcNOkZLr5e1bo2tc0q4', 'word': 'peas'},
    {'id': 'QmqnoedYpBVtMToGCQ5Y', 'word': 'pennywort'},
    {'id': 'ojxHyX0fbKdidAoV7X39', 'word': 'persimmon'},
    {'id': 'R9YfGYqWJ0VY5bELndvP', 'word': 'pineapple'},
    {'id': '2qpF7TCDctNABvy5Kqfl', 'word': 'plum'},
    {'id': 'WCDG4uebIjBMUngvm5py', 'word': 'pomegranate'},
    {'id': 'P8DgnCIZ02tiHtHUHWdG', 'word': 'pomelo'},
    {'id': 'vtput1kqTFIOWGLrBu6b', 'word': 'pond apple'},
    {'id': 'i7xhRBK1jftcnz1c5FuC', 'word': 'potato'},
    {'id': 'kQ74AaDNEO6QzcdiTxuv', 'word': 'pumpkin'},
    {'id': '5AXZN9iuM3XPZP22vLrt', 'word': 'radicchio'},
    {'id': 'Y6gEHtB3SIrSGhCkXxEA', 'word': 'radish'},
    {'id': 'TB4H08OZk4MEN1Iiy8ac', 'word': 'rambutan'},
    {'id': 'Q79btQKt7kGZiAVyZAHY', 'word': 'raspberry'},
    {'id': 'jq1ZA6QFlM4SSfWMrw2I', 'word': 'sapodilla'},
    {'id': 'cJDSLD2IHOFaK4IsYSMd', 'word': 'scallion'},
    {'id': 'czYrwiz5OnMkjarpEom5', 'word': 'shallot'},
    {'id': 'ekC66TMYZ9kwdrqY9xwo', 'word': 'soursop'},
    {'id': '60dlj4TJe2JZ20VA7oUc', 'word': 'star apple'},
    {'id': 'rX02ezy448xmczrp97Qg', 'word': 'star fruit'},
    {'id': '3WjG1lnDQsC8KzWJvk3z', 'word': 'strawberry'},
    {'id': '3bpyFbvkC3oyznMWffAU', 'word': 'string bean'},
    {'id': 'gF8kRQiiPkc4sxfIU6tP', 'word': 'sweet potato'},
    {'id': 'Yc1F0YNznC1k9DihN4eU', 'word': 'tamarind'},
    {'id': 'RlA3RNOIp5xUmF5RYTxt', 'word': 'tomato'},
    {'id': '0BwkJ1fnC5Era9E4GDsw', 'word': 'turmeric'},
    {'id': 'EWfrX1ijnRGNKFDhdd31', 'word': 'turnip'},
    {'id': 'kFZPma8Bq7xrKCnuzf5Z', 'word': 'walnut'},
    {'id': '2nyF4GgrLY0cPpN1S95x', 'word': 'water caltrop'},
    {'id': 'PMuMnIq4rkRP1cSIOL9W', 'word': 'watermelon'},
    {'id': 'ixGoGkK5Xk5qNzrf2Fsx', 'word': 'wax gourd'},
    {'id': 'yhoQnX2gRM76jbu61K1V', 'word': 'yam'},
]
